 labels:
   - name: High
     color: CC0000
     description: High priority
   - name: Medium
     color: 336699
     description: Medium priority
   - name: Low
     color: 336699
     description: Low priority