 categories:
  - keyword: ui
    label:
      name: 'UI :desktop_computer:' 
      color: 000007
      description: UI related
  - keyword: backend
    label:
      name: 'Backend :wrench:'
      color: 005500
      description: Backend related
  - keyword: security
    label:
      name: 'Security :lock_with_ink_pen:'
      color: 000075
      description: Security related